import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import Header from '@/components/header/Header'
import photo from '@/assets/photos/home.svg'
import { HomeStyle } from '../styles/homeStyle'

const Home: NextPage = () => {
  return (
    <HomeStyle>
      <Head>
        <title>CO2 App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <Header />
        <h1>Calcule suas emissões de carbono</h1>
        <p>
          Veja nosso relatório de emissões e se informe com dados atuais do
          IPCC.
        </p>
        <div className='buttons'>
          <Link href={'/calculate'}>
            <button className='btnPrimary'>Calcular</button>
          </Link>
          <Link href={'/info'}>
            <button className='btnSecundary'>Saiba mais</button>
          </Link>
        </div>
      </div>
      {/*eslint-disable-next-line @typescript-eslint/no-unsafe-assignment*/}
      <Image src={photo} alt='Vegetação' />
    </HomeStyle>
  )
}

export default Home
